from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import JSON, Uuid, engine_from_config, pool
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID

from app.core.config import settings
from app.core.db import Base
from app.models import (  # noqa: F401
    CatalogueMeta,
    DeepSkyObject,
    ObservationAssessment,
    SavedLocation,
    User,
    WeatherForecastCache,
)

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ConfigParser interpolates '%', so escape URLs before storing them on the config.
config.set_main_option("sqlalchemy.url", settings.database_url.replace("%", "%%"))
target_metadata = Base.metadata


def render_item(type_, obj, autogen_context):
    """Render ORM aliases so autogenerated migrations stay dialect-portable."""
    if type_ == "server_default" and obj is not None:
        rendered = str(getattr(obj, "arg", obj)).lower()
        if "current_timestamp" in rendered or rendered in {"now()", "now"}:
            return "sa.func.now()"
        return False
    if type_ != "type":
        return False
    if isinstance(obj, (Uuid, PGUUID)):
        autogen_context.imports.add("from app.models.types import JSON_DOC, UUID_PK")
        return "UUID_PK"
    if isinstance(obj, (JSON, JSONB)):
        autogen_context.imports.add("from app.models.types import JSON_DOC, UUID_PK")
        return "JSON_DOC"
    return False


def process_revision_directives(context_, revision, directives):
    """Refuse to write an empty revision when autogenerate finds no model changes."""
    cmd_opts = getattr(config, "cmd_opts", None)
    if cmd_opts is None or not getattr(cmd_opts, "autogenerate", False):
        return
    script = directives[0]
    if script.upgrade_ops.is_empty():
        directives[:] = []
        print("No schema changes to autogenerate.")


def _configure(**kwargs) -> None:
    context.configure(
        target_metadata=target_metadata,
        compare_type=True,
        render_item=render_item,
        process_revision_directives=process_revision_directives,
        **kwargs,
    )


def run_migrations_offline() -> None:
    _configure(
        url=settings.database_url,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=settings.database_url.startswith("sqlite"),
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        {"sqlalchemy.url": settings.database_url},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        _configure(
            connection=connection,
            render_as_batch=connection.dialect.name == "sqlite",
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
