"""initial schema from ORM

Revision ID: bca1057e2116
Revises:
Create Date: 2026-09-02 11:49:21.366332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types import JSON_DOC, UUID_PK

# revision identifiers, used by Alembic.
revision: str = "bca1057e2116"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalogue_meta",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deep_sky_objects",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("primary_name", sa.String(length=128), nullable=False),
        sa.Column("common_name", sa.String(length=128), nullable=True),
        sa.Column("catalogue_ids", JSON_DOC, nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("friendly_type", sa.String(length=64), nullable=False),
        sa.Column("ra", sa.Float(), nullable=False),
        sa.Column("dec", sa.Float(), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("angular_size", sa.Float(), nullable=True),
        sa.Column("beginner_prior", sa.Integer(), nullable=False),
        sa.Column("search_text", sa.String(length=1024), nullable=False),
        sa.Column("metadata", JSON_DOC, nullable=False),
        sa.Column("images", JSON_DOC, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deep_sky_objects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deep_sky_objects_beginner_prior"), ["beginner_prior"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deep_sky_objects_object_type"), ["object_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deep_sky_objects_primary_name"), ["primary_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deep_sky_objects_search_text"), ["search_text"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", UUID_PK, nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "weather_forecast_cache",
        sa.Column("cell_key", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", JSON_DOC, nullable=False),
        sa.PrimaryKeyConstraint("cell_key"),
    )
    with op.batch_alter_table("weather_forecast_cache", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_weather_forecast_cache_fetched_at"), ["fetched_at"], unique=False
        )

    op.create_table(
        "saved_locations",
        sa.Column("id", UUID_PK, nullable=False),
        sa.Column("user_id", UUID_PK, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_saved_location_user_name"),
    )
    with op.batch_alter_table("saved_locations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saved_locations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "observation_assessments",
        sa.Column("id", UUID_PK, nullable=False),
        sa.Column("saved_location_id", UUID_PK, nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assessment_hash", sa.String(length=64), nullable=False),
        sa.Column("assessment", JSON_DOC, nullable=False),
        sa.ForeignKeyConstraint(["saved_location_id"], ["saved_locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("observation_assessments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_observation_assessments_assessment_hash"),
            ["assessment_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_observation_assessments_generated_at"), ["generated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_observation_assessments_saved_location_id"),
            ["saved_location_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("observation_assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observation_assessments_saved_location_id"))
        batch_op.drop_index(batch_op.f("ix_observation_assessments_generated_at"))
        batch_op.drop_index(batch_op.f("ix_observation_assessments_assessment_hash"))

    op.drop_table("observation_assessments")
    with op.batch_alter_table("saved_locations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_locations_user_id"))

    op.drop_table("saved_locations")
    with op.batch_alter_table("weather_forecast_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weather_forecast_cache_fetched_at"))

    op.drop_table("weather_forecast_cache")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("deep_sky_objects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deep_sky_objects_search_text"))
        batch_op.drop_index(batch_op.f("ix_deep_sky_objects_primary_name"))
        batch_op.drop_index(batch_op.f("ix_deep_sky_objects_object_type"))
        batch_op.drop_index(batch_op.f("ix_deep_sky_objects_beginner_prior"))

    op.drop_table("deep_sky_objects")
    op.drop_table("catalogue_meta")
    # ### end Alembic commands ###
